on:
  push:
jobs:
  reproduction:
    runs-on: macos-latest
    env:
      HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: Homebrew/actions/setup-homebrew@main
      with:
        stable: true
    - run: sh reproduction.sh
